export default {
  "background-default": "#ffffff",
  "background-inverted": "#272E35",
  "background-neutral": "#555F6D",
  "background-informative": "#3062D4",
  "background-positive": "rgba(29, 124, 77, 1)",
  "background-warning": "rgba(245, 150, 56, 1)",
  "background-negative": "rgba(197, 52, 52, 1)",
  "background-brand": "#3062D4",
  "background-subtle-neutral": "#F5F7F9",
  "background-subtle-informative": "#F5F7F9",
  "background-subtle-positive": "#F5F7F9",
  "background-subtle-warning": "#F5F7F9",
  "background-subtle-negative": "#F5F7F9",
  "background-subtle-brand": "#F5F7F9",
  "background-surface-neutral": "#FBFCFD",
  "background-surface-informative": "#FAFBFF",
  "background-surface-positive": "#FBFEFC",
  "background-surface-warning": "#FFFCFA",
  "background-surface-negative": "#FFFAFA",
  "background-surface-brand": "#FAFBFF",
  "background-default-dimmer": "rgba(25, 39, 58, 0.74)",
};
