export default {
  "border-default": "#E9ECEF",
  "border-default-alpha": "rgba(16, 40, 72, 0.09)",
  "border-neutral": "#555F6D",
  "border-informative": "#3062D4",
  "border-positive": "rgba(29, 124, 77, 1)",
  "border-warning": "rgba(245, 150, 56, 1)",
  "border-negative": "rgba(197, 52, 52, 1)",
  "border-brand": "rgba(48, 98, 212, 1)",
  "border-subtle-neutral": "#CFD6DD",
  "border-subtle-informative": "#CDDDFF",
  "border-subtle-positive": "#C2EBD5",
  "border-subtle-warning": "#FFD4A8",
  "border-subtle-negative": "#FCCFCF",
  "border-subtle-brand": "#CDDDFF",
  "border-inverted": "#ffffff",
};
